CREATE USER 'paula'@'%' IDENTIFIED BY '123';
GRANT ALL PRIVILEGES ON bookstore.* TO 'paula'@'%' WITH GRANT OPTION;

CREATE USER 'kimsy'@'%' IDENTIFIED BY '456';
GRANT ALL PRIVILEGES ON bookstore.* TO 'kimsy'@'%' WITH GRANT OPTION;

CREATE USER 'mie'@'%' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON bookstore_db.* TO 'mie'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;
